services:
  predictions:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
